name: Bug Report
description: Report a bug or unexpected behavior in BotV2
title: "[BUG]: "
labels: ["bug", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        Please provide as much detail as possible to help us investigate.

  - type: input
    id: version
    attributes:
      label: BotV2 Version
      description: What version of BotV2 are you running?
      placeholder: "e.g., 1.1.0"
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - Trading Engine
        - Dashboard
        - Risk Management
        - Strategies
        - Exchange Integration
        - Backtesting
        - Configuration
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug
      placeholder: Describe what happened...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe expected behavior...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Configure...
        2. Run...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Please copy and paste any relevant log output
      render: shell

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Linux
        - macOS
        - Windows
        - Docker
    validations:
      required: true

  - type: input
    id: python
    attributes:
      label: Python Version
      placeholder: "e.g., 3.11.4"

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues for duplicates
          required: true
        - label: I have read the documentation
          required: true
